[book]
title = "Telltale"
authors = ["Sam Hart"]
language = "en"
src = "docs"

[build]
build-dir = "docs/book"

[output.html]
preferred-dark-theme = "rust"
additional-js = ["docs/mermaid.min.js", "docs/mermaid-init.js"]

[output.html.playground]
editable = false

[preprocessor.mermaid]
