[book]
title = "Rumpsteak Aura"
authors = ["Sam Hart"]
language = "en"
src = "docs"

[build]
build-dir = "docs/book"

[output.html]
preferred-dark-theme = "rust"
theme = "theme"

[output.html.playground]
editable = false

[preprocessor.mermaid]
